version: '3.8'

services:
  api:
    build: .
    container_name: extrator-etiquetas
    ports:
      - "8001:8001"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      UPLOAD_FOLDER: ./temp
    volumes:
      - .:/app  # <--- MUDANÇA AQUI: MAPEIA A RAIZ INTEIRA PARA O /APP DO CONTAINER
    networks:
      - etiquetas-network

networks:
  etiquetas-network:
    driver: bridge
